name: 每5分钟-运行一次node
on: 
  # 手动触发
  workflow_dispatch:
  # 定时器
  schedule:
    - cron: "*/12 * * * *"
env:  
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
            
      - name: 更新时区
        id: date
        run: |
          sudo timedatectl set-timezone "$TZ"
          
      - name: 下载rendie-chrome扩展       
        run: |        
          git clone https://github.com/rendie-com/rendie-chrome -b main ./node/rendie-chrome
             
      - name: 运行node       
        run: |      
          mkdir -p ./error/
          cd ./node/
          npm i  
          node ./5minute.js   
        env:
          NODE_SHOPEE_ACCESS_TOKEN: ${{ secrets.NODE_SHOPEE_ACCESS_TOKEN }}  
          NODE_SHOPEE_REFRESH_TOKEN: ${{ secrets.NODE_SHOPEE_REFRESH_TOKEN }}
    
      - name: 部署nextjs
        uses: JamesIves/github-pages-deploy-action@v4       
        with: 
            branch: main
            folder: error/
            target-folder: error/
      - name: 删除运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 0
