name: 5分钟-运行nextjs和node
on: 
  # 手动触发
  workflow_dispatch:
  # 定时器
  # schedule:
   #  - cron: "*/5 * * * *"
env:  
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
            
      - name: 更新时区
        id: date
        run: |
          sudo timedatectl set-timezone "$TZ"
          
      - name: 下载rendie-chrome扩展       
        run: |        
          git clone https://github.com/rendie-com/rendie-chrome -b main rendie-chrome
             
      - name: 运行node       
        run: |         
          cd ./node/
          npm i  
          node ./index.js   
        env:
          NODE_SHOPEE_ACCESS_TOKEN: ${{ secrets.NODE_SHOPEE_ACCESS_TOKEN }}  
          NODE_SHOPEE_REFRESH_TOKEN: ${{ secrets.NODE_SHOPEE_REFRESH_TOKEN }}
    
